/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as VehiclesIdRouteImport } from './routes/vehicles_.$id'
import { Route as BranchesIdRouteImport } from './routes/branches_.$id'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIdRoute = VehiclesIdRouteImport.update({
  id: '/vehicles_/$id',
  path: '/vehicles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIdRoute = BranchesIdRouteImport.update({
  id: '/branches_/$id',
  path: '/branches/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/vehicles': typeof VehiclesRoute
  '/branches/$id': typeof BranchesIdRoute
  '/vehicles/$id': typeof VehiclesIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/vehicles': typeof VehiclesRoute
  '/branches/$id': typeof BranchesIdRoute
  '/vehicles/$id': typeof VehiclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/vehicles': typeof VehiclesRoute
  '/branches_/$id': typeof BranchesIdRoute
  '/vehicles_/$id': typeof VehiclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/branches'
    | '/vehicles'
    | '/branches/$id'
    | '/vehicles/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/branches' | '/vehicles' | '/branches/$id' | '/vehicles/$id'
  id:
    | '__root__'
    | '/auth'
    | '/branches'
    | '/vehicles'
    | '/branches_/$id'
    | '/vehicles_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  BranchesRoute: typeof BranchesRoute
  VehiclesRoute: typeof VehiclesRoute
  BranchesIdRoute: typeof BranchesIdRoute
  VehiclesIdRoute: typeof VehiclesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles_/$id': {
      id: '/vehicles_/$id'
      path: '/vehicles/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof VehiclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches_/$id': {
      id: '/branches_/$id'
      path: '/branches/$id'
      fullPath: '/branches/$id'
      preLoaderRoute: typeof BranchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  BranchesRoute: BranchesRoute,
  VehiclesRoute: VehiclesRoute,
  BranchesIdRoute: BranchesIdRoute,
  VehiclesIdRoute: VehiclesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
